//
// Autogenerated by Thrift Compiler (0.14.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./Task_types');
//HELPER FUNCTIONS AND STRUCTURES

var Reports_saveReport_args = function(args) {
  this.report = null;
  if (args) {
    if (args.report !== undefined && args.report !== null) {
      this.report = Thrift.copyMap(args.report, [Thrift.copyList, null]);
    }
  }
};
Reports_saveReport_args.prototype = {};
Reports_saveReport_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.MAP) {
        this.report = {};
        var _rtmp321 = input.readMapBegin();
        var _size20 = _rtmp321.size || 0;
        for (var _i22 = 0; _i22 < _size20; ++_i22) {
          var key23 = null;
          var val24 = null;
          key23 = input.readString();
          val24 = [];
          var _rtmp326 = input.readSetBegin();
          var _size25 = _rtmp326.size || 0;
          for (var _i27 = 0; _i27 < _size25; ++_i27) {
            var elem28 = null;
            elem28 = input.readString();
            val24.push(elem28);
          }
          input.readSetEnd();
          this.report[key23] = val24;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Reports_saveReport_args.prototype.write = function(output) {
  output.writeStructBegin('Reports_saveReport_args');
  if (this.report !== null && this.report !== undefined) {
    output.writeFieldBegin('report', Thrift.Type.MAP, 1);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.SET, Thrift.objectLength(this.report));
    for (var kiter29 in this.report) {
      if (this.report.hasOwnProperty(kiter29)) {
        var viter30 = this.report[kiter29];
        output.writeString(kiter29);
        output.writeSetBegin(Thrift.Type.STRING, viter30.length);
        for (var iter31 in viter30) {
          if (viter30.hasOwnProperty(iter31)) {
            iter31 = viter30[iter31];
            output.writeString(iter31);
          }
        }
        output.writeSetEnd();
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Reports_saveReport_result = function(args) {
  this.success = null;
  this.protocolException = null;
  if (args instanceof ttypes.ProtocolException) {
    this.protocolException = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.protocolException !== undefined && args.protocolException !== null) {
      this.protocolException = args.protocolException;
    }
  }
};
Reports_saveReport_result.prototype = {};
Reports_saveReport_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.protocolException = new ttypes.ProtocolException();
        this.protocolException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Reports_saveReport_result.prototype.write = function(output) {
  output.writeStructBegin('Reports_saveReport_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.protocolException !== null && this.protocolException !== undefined) {
    output.writeFieldBegin('protocolException', Thrift.Type.STRUCT, 1);
    this.protocolException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ReportsClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
ReportsClient.prototype = {};
ReportsClient.prototype.seqid = function() { return this._seqid; };
ReportsClient.prototype.new_seqid = function() { return this._seqid += 1; };

ReportsClient.prototype.saveReport = function(report, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_saveReport(report);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_saveReport(report);
  }
};

ReportsClient.prototype.send_saveReport = function(report) {
  var output = new this.pClass(this.output);
  var params = {
    report: report
  };
  var args = new Reports_saveReport_args(params);
  try {
    output.writeMessageBegin('saveReport', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

ReportsClient.prototype.recv_saveReport = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Reports_saveReport_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.protocolException) {
    return callback(result.protocolException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('saveReport failed: unknown result');
};
var ReportsProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
ReportsProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
ReportsProcessor.prototype.process_saveReport = function(seqid, input, output) {
  var args = new Reports_saveReport_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.saveReport.length === 1) {
    Q.fcall(this._handler.saveReport.bind(this._handler),
      args.report
    ).then(function(result) {
      var result_obj = new Reports_saveReport_result({success: result});
      output.writeMessageBegin("saveReport", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.ProtocolException) {
        result = new Reports_saveReport_result(err);
        output.writeMessageBegin("saveReport", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("saveReport", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.saveReport(args.report, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.ProtocolException) {
        result_obj = new Reports_saveReport_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("saveReport", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("saveReport", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
