/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Reports_H
#define Reports_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "Task_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ReportsIf {
 public:
  virtual ~ReportsIf() {}
  virtual bool saveReport(const Report& report) = 0;
};

class ReportsIfFactory {
 public:
  typedef ReportsIf Handler;

  virtual ~ReportsIfFactory() {}

  virtual ReportsIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ReportsIf* /* handler */) = 0;
};

class ReportsIfSingletonFactory : virtual public ReportsIfFactory {
 public:
  ReportsIfSingletonFactory(const ::std::shared_ptr<ReportsIf>& iface) : iface_(iface) {}
  virtual ~ReportsIfSingletonFactory() {}

  virtual ReportsIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ReportsIf* /* handler */) {}

 protected:
  ::std::shared_ptr<ReportsIf> iface_;
};

class ReportsNull : virtual public ReportsIf {
 public:
  virtual ~ReportsNull() {}
  bool saveReport(const Report& /* report */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _Reports_saveReport_args__isset {
  _Reports_saveReport_args__isset() : report(false) {}
  bool report :1;
} _Reports_saveReport_args__isset;

class Reports_saveReport_args {
 public:

  Reports_saveReport_args(const Reports_saveReport_args&);
  Reports_saveReport_args& operator=(const Reports_saveReport_args&);
  Reports_saveReport_args() {
  }

  virtual ~Reports_saveReport_args() noexcept;
  Report report;

  _Reports_saveReport_args__isset __isset;

  void __set_report(const Report& val);

  bool operator == (const Reports_saveReport_args & rhs) const
  {
    if (!(report == rhs.report))
      return false;
    return true;
  }
  bool operator != (const Reports_saveReport_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Reports_saveReport_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Reports_saveReport_pargs {
 public:


  virtual ~Reports_saveReport_pargs() noexcept;
  const Report* report;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Reports_saveReport_result__isset {
  _Reports_saveReport_result__isset() : success(false), protocolException(false) {}
  bool success :1;
  bool protocolException :1;
} _Reports_saveReport_result__isset;

class Reports_saveReport_result {
 public:

  Reports_saveReport_result(const Reports_saveReport_result&);
  Reports_saveReport_result& operator=(const Reports_saveReport_result&);
  Reports_saveReport_result() : success(0) {
  }

  virtual ~Reports_saveReport_result() noexcept;
  bool success;
  ProtocolException protocolException;

  _Reports_saveReport_result__isset __isset;

  void __set_success(const bool val);

  void __set_protocolException(const ProtocolException& val);

  bool operator == (const Reports_saveReport_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(protocolException == rhs.protocolException))
      return false;
    return true;
  }
  bool operator != (const Reports_saveReport_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Reports_saveReport_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Reports_saveReport_presult__isset {
  _Reports_saveReport_presult__isset() : success(false), protocolException(false) {}
  bool success :1;
  bool protocolException :1;
} _Reports_saveReport_presult__isset;

class Reports_saveReport_presult {
 public:


  virtual ~Reports_saveReport_presult() noexcept;
  bool* success;
  ProtocolException protocolException;

  _Reports_saveReport_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ReportsClient : virtual public ReportsIf {
 public:
  ReportsClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ReportsClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool saveReport(const Report& report);
  void send_saveReport(const Report& report);
  bool recv_saveReport();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ReportsProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<ReportsIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ReportsProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_saveReport(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ReportsProcessor(::std::shared_ptr<ReportsIf> iface) :
    iface_(iface) {
    processMap_["saveReport"] = &ReportsProcessor::process_saveReport;
  }

  virtual ~ReportsProcessor() {}
};

class ReportsProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ReportsProcessorFactory(const ::std::shared_ptr< ReportsIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< ReportsIfFactory > handlerFactory_;
};

class ReportsMultiface : virtual public ReportsIf {
 public:
  ReportsMultiface(std::vector<std::shared_ptr<ReportsIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ReportsMultiface() {}
 protected:
  std::vector<std::shared_ptr<ReportsIf> > ifaces_;
  ReportsMultiface() {}
  void add(::std::shared_ptr<ReportsIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool saveReport(const Report& report) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->saveReport(report);
    }
    return ifaces_[i]->saveReport(report);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ReportsConcurrentClient : virtual public ReportsIf {
 public:
  ReportsConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ReportsConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool saveReport(const Report& report);
  int32_t send_saveReport(const Report& report);
  bool recv_saveReport(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
