// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Search.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class SearchHandler : virtual public SearchIf {
 public:
  SearchHandler() {
    // Your initialization goes here
  }

  void search(SearchState& _return, const std::string& query, const int32_t limit) {
    // Your implementation goes here
    printf("search\n");
  }

  void fetch(FetchResult& _return, const SearchState& state) {
    // Your implementation goes here
    printf("fetch\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<SearchHandler> handler(new SearchHandler());
  ::std::shared_ptr<TProcessor> processor(new SearchProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

